<?php

namespace App\Repositories;

use App\Presenters\FaleConoscoAssuntoPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Models\FaleConoscoAssunto;
use App\Validators\FaleConoscoAssuntoValidator;

/**
 * Class FaleConoscoAssuntoRepositoryEloquent
 * @package namespace App\Repositories;
 */
class FaleConoscoAssuntoRepositoryEloquent extends BaseRepository implements FaleConoscoAssuntoRepository
{
    protected $skipPresenter = true;

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return FaleConoscoAssunto::class;
    }

    public function presenter()
    {
        return FaleConoscoAssuntoPresenter::class; // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
}
